config/routes.rb
Rails.application.routes.draw do
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all
  end

  def show
    @kitten = Kitten.find(params[:id])
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      flash[:success] = "Kitten added!"
      redirect_to @kitten
    else
      render :new
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update_attributes(kitten_params)
      flash[:success] = "Kitten updated!"
      redirect_to @kitten
    else
      render :edit
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    flash[:success] = "Kitten destroyed!"
    redirect_to root_path
  end

  private
    def kitten_params
      params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with scope: :kitten, url: yield(:url), method: yield(:method), local: true do |f| %>
  <% if @kitten.errors.any? %>
    <% @kitten.errors.full_messages.each do |e| %>
      <ul>
        <li><%= e %></li>
      </ul>
    <% end %>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>
  <%= f.label :age %>
  <%= f.number_field :age %>
  <br/>
  <%= f.label :cuteness %>
  <%= f.number_field :cuteness, in: 1.0..10.0, step: 0.5 %>
  <br/>
  <%= f.label :softness %>
  <%= f.number_field :softness, in: 1.0..10.0, step: 0.5 %>
  <br/>
  <%= f.submit yield(:button_text) %>
<% end %>

app/views/kittens/_kitten.html.erb
<tr>
  <td><%= kitten.id %></td>
  <td><%= kitten.name %></td>
  <td><%= kitten.age %></td>
  <td><%= kitten.cuteness %></td>
  <td><%= kitten.softness %></td>
  <td><%= link_to "Show", kitten %></td>
  <td><%= link_to "Edit", edit_kitten_path(kitten) %></td>
  <td><%= link_to "Delete", kitten, method: :delete %></td>
</tr>

app/views/kittens/edit.html.erb
<% provide(:url, kitten_path(@kitten)) %>
<% provide(:button_text, "Update kitten") %>
<% provide(:method, :patch) %>

<h1>Kittens edit</h1>

<%= render "form" %>
<br/>
<%= link_to "Delete this kitten", @kitten, method: :delete %>

app/views/kittens/index.html.erb
<h1>Kittens index</h1>

<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Age</th>
    <th>Cuteness</th>
    <th>Softness</th>
  </tr>
  <%= render @kittens %>
</table>

<%= link_to "Add a kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<% provide(:url, kittens_path) %>
<% provide(:button_text, "Create kitten") %>
<% provide(:method, :post) %>

<h1>Kittens new</h1>

<%= render "form" %>

app/views/kittens/show.html.erb
<h1>Kittens show</h1>
<h2><%= @kitten.name %></h2>
<span>Age: <%=@kitten.age %> | Cuteness: <%= @kitten.cuteness %> | Softness: <%= @kitten.softness %></span>
<br/>
<%= link_to "Delete this kitten", @kitten, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <%= content_tag :div, value, class: "flash-#{key}" %>
    <% end %>

    <%= yield %>
  </body>
</html>